# Generated by Django 6.0.6 on 2026-06-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0003_remove_estudiante_anio_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='anio_nacimiento',
            field=models.IntegerField(default=2000),
        ),
    ]
